version: '4.0'

services:
  frontend:
    image: atts_frontend
    build:
      context: ./front
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
        REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
        REACT_APP_KEYCLOAK_URL: ${REACT_APP_KEYCLOAK_URL}
        REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
        REACT_APP_KEYCLOAK_RESOURCE: ${REACT_APP_KEYCLOAK_RESOURCE}
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: my-atts-frontend
#  keycloak:
#    image: jboss/keycloak:latest
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#      DB_VENDOR: h2
#    volumes:
#      - keycloak_data:/opt/jboss/keycloak/standalone/data
#    ports:
#      - 8080:8080
#  db:
#    image: mysql:latest
#    container_name: atts_db
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: 'atts'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'atts'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'atts'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'root'
##    command: --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
#    volumes:
#      - ./mysql:/var/lib/mysql
    
#volumes:
#  keycloak_data: